### ISSUE TITLE
Stops Responding

### ISSUE THREAD

**Issue by Zeldeza** [MiniMage7/MiniMage7.github.io#2]
More complicated, larger puzzles aren't solvable using the program as your window stops responding, and waiting doesn't seem to do anything as the page just hangs forever - waited over an hour and nothing changed.

**Comment by MiniMage7** [comment]
Hey, sorry about this, I forgot to change the warning after some testing. Due to the limitations of statically served websites and browsers, some of the extremely large puzzles will break the website. If there is enough interest I can make a locally hosted version that will be able to get around this, but I don't currently have intentions to set up a full server for this project to handle larger solve requests online.

**Comment by Zeldeza** [comment]
That's unfortunate - The fact it still works for smaller puzzles is a good thing tough. 
This seems to be the only thing online that I can find that helps with Islands of Insight puzzles - There's not enough information online about this game unfortunately.

**Comment by isakara** [comment]
Really, if it's not capable of solving all the puzzles, there's no point.

**Comment by ayourk** [comment]
I have a modified version working that exports and imports Puzzle JSON so that it could potentially be used in an external program and parsed/solved that way.  Eventually, I hope to be able to import puzzle solves as JSON too.  I'll do a Pull Request if @MiniMage7 wishes for the beginnings of Import/Export functionality.  I've already submitted a Pull Request for Glyphs to make it easier for color blind people.

**Comment by MiniMage7** [comment]
> Really, if it's not capable of solving all the puzzles, there's no point.

Hey, I'm sorry but I don't have the financial means to host a full server to solve the largest puzzles. The website as it is already leaks money. If the community wants the website to have full support for all puzzles, I'm sure we can work together to find a way to fund a host for it.

**Comment by ayourk** [comment]
> > Really, if it's not capable of solving all the puzzles, there's no point.
> 
> Hey, I'm sorry but I don't have the financial means to host a full server to solve the largest puzzles. The website as it is already leaks money. If the community wants the website to have full support for all puzzles, I'm sure we can work together to find a way to fund a host for it.

I have access to a full shell host and could put it up on there.

**Comment by MiniMage7** [comment]
> > > Really, if it's not capable of solving all the puzzles, there's no point.
> > 
> > 
> > Hey, I'm sorry but I don't have the financial means to host a full server to solve the largest puzzles. The website as it is already leaks money. If the community wants the website to have full support for all puzzles, I'm sure we can work together to find a way to fund a host for it.
> 
> I have access to a full shell host and could put it up on there.

That could probably work. The biggest issue is that the only next step for optimization I see is using full multithreading (and with another dreaded rewrite to something like C or Rust to support it) which could quickly eat a lot of resources. I realized pretty fast while working on this that most optimizations to solves are expensive and slow down the average cases a lot.

**Comment by ayourk** [comment]
> > > > Really, if it's not capable of solving all the puzzles, there's no point.
> > > 
> > > 
> > > Hey, I'm sorry but I don't have the financial means to host a full server to solve the largest puzzles. The website as it is already leaks money. If the community wants the website to have full support for all puzzles, I'm sure we can work together to find a way to fund a host for it.
> > 
> > 
> > I have access to a full shell host and could put it up on there.
> 
> That could probably work. The biggest issue is that the only next step for optimization I see is using full multithreading (and with another dreaded rewrite to something like C or Rust to support it) which could quickly eat a lot of resources. I realized pretty fast while working on this that most optimizations to solves are expensive and slow down the average cases a lot.

If you could write a python script that parses the following JSON, I can probably rewrite it in C or something else.  I am fairly weak at JavaScript.  This solver could probably even be converted to Electron/NodeJS.

```
{"cols":11, "rows":12, "tiles":{"2":1, "8":1, "12":1, "13":7, "14":7, "19":2, "20":1, "21":8, "22":2, "23":2, "24":1, "25":7, "29":7, "30":1, "31":2, "32":8, "33":2, "34":2, "35":8, "36":2, "40":2, "41":7, "42":8, "43":2, "44":8, "45":8, "46":2, "47":8, "51":7, "52":2, "53":2, "54":8, "55":-1, "56":-1, "57":6, "58":-1, "59":4, "62":-1, "63":6, "64":-1, "65":-1, "66":-1, "67":-1, "68":6, "69":-1, "70":4, "71":3, "73":-1, "74":6, "75":-1, "76":-1, "77":1, "78":6, "79":1, "80":1, "81":6, "82":8, "84":1, "85":1, "86":6, "87":1, "88":-1, "89":-1, "90":-1, "91":5, "92":5, "93":3, "94":3, "95":5, "96":-1, "97":-1, "98":-1, "99":-1, "100":-1, "101":-1, "102":6, "103":4, "104":5, "105":6, "106":5, "107":-1, "108":-1, "109":-1, "110":-1, "111":-1, "112":-1, "113":6, "114":4, "115":6, "116":5, "117":6, "118":-1, "119":-1, "120":-1, "121":-1, "122":-1, "123":-1, "124":3, "125":3, "126":4, "127":4, "128":3, "129":-1, "130":-1, "131":-1}}
```

**Comment by MiniMage7** [comment]
> > > > > Really, if it's not capable of solving all the puzzles, there's no point.
> > > > 
> > > > 
> > > > Hey, I'm sorry but I don't have the financial means to host a full server to solve the largest puzzles. The website as it is already leaks money. If the community wants the website to have full support for all puzzles, I'm sure we can work together to find a way to fund a host for it.
> > > 
> > > 
> > > I have access to a full shell host and could put it up on there.
> > 
> > 
> > That could probably work. The biggest issue is that the only next step for optimization I see is using full multithreading (and with another dreaded rewrite to something like C or Rust to support it) which could quickly eat a lot of resources. I realized pretty fast while working on this that most optimizations to solves are expensive and slow down the average cases a lot.
> 
> If you could write a python script that parses the following JSON, I can probably rewrite it in C or something else. I am fairly weak at JavaScript. This solver could probably even be converted to Electron/NodeJS.
> 
> ```
> {"cols":11, "rows":12, "tiles":{"2":1, "8":1, "12":1, "13":7, "14":7, "19":2, "20":1, "21":8, "22":2, "23":2, "24":1, "25":7, "29":7, "30":1, "31":2, "32":8, "33":2, "34":2, "35":8, "36":2, "40":2, "41":7, "42":8, "43":2, "44":8, "45":8, "46":2, "47":8, "51":7, "52":2, "53":2, "54":8, "55":-1, "56":-1, "57":6, "58":-1, "59":4, "62":-1, "63":6, "64":-1, "65":-1, "66":-1, "67":-1, "68":6, "69":-1, "70":4, "71":3, "73":-1, "74":6, "75":-1, "76":-1, "77":1, "78":6, "79":1, "80":1, "81":6, "82":8, "84":1, "85":1, "86":6, "87":1, "88":-1, "89":-1, "90":-1, "91":5, "92":5, "93":3, "94":3, "95":5, "96":-1, "97":-1, "98":-1, "99":-1, "100":-1, "101":-1, "102":6, "103":4, "104":5, "105":6, "106":5, "107":-1, "108":-1, "109":-1, "110":-1, "111":-1, "112":-1, "113":6, "114":4, "115":6, "116":5, "117":6, "118":-1, "119":-1, "120":-1, "121":-1, "122":-1, "123":-1, "124":3, "125":3, "126":4, "127":4, "128":3, "129":-1, "130":-1, "131":-1}}
> ```

That would be fairly easy, but that's a little bit down the path from where we're currently at. I'll look into making a better setup for the whole thing over the weekend.

**Comment by Xepho1** [comment]
Also playing Island of insights and stuck on one puzzle in particular that the website cant handle. The local version would be nice because this probably wont be the only one I get stuck on.
![ioipuzzle](https://github.com/MiniMage7/MiniMage7.github.io/assets/161029933/0c23d63e-79ae-4670-8c52-8a700d22bae5)

**Comment by ayourk** [comment]
> Also playing Island of insights and stuck on one puzzle in particular that the website cant handle. The local version would be nice because this probably wont be the only one I get stuck on. ![ioipuzzle](https://private-user-images.githubusercontent.com/161029933/307310442-0c23d63e-79ae-4670-8c52-8a700d22bae5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2OTY1ODQsIm5iZiI6MTcwODY5NjI4NCwicGF0aCI6Ii8xNjEwMjk5MzMvMzA3MzEwNDQyLTBjMjNkNjNlLTc5YWUtNDY3MC04YzUyLThhNzAwZDIyYmFlNS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyM1QxMzUxMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YWNiYmU4ODI1MjRhZTAyYjkzN2ZmM2E0YjAwNTJlNGU4NDFlZTRmZGIwNmJiZGEwZGE2M2U0ZGFlOTc3MTYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ckkXb4l-3kXYzoOOKtDcEolaZlJQZ_qJyJXkqCa6n8w)

I'm currently stuck on 3 of them, and this is one of the 3.  Equivalent Puzzle JSON:
```
{ "height": 23, "width": 9, "board": [[0,0,0,0,0,0,0,4,0], [0,0,0,0,0,0,0,4,0], [0,0,0,0,0,0,0,1,0], [0,0,0,0,0,0,0,4,0], [0,0,0,0,0,0,0,5,0], [0,0,0,0,0,0,0,5,0], [0,0,0,0,6,0,0,2,0], [0,0,0,0,5,0,0,2,0], [0,0,0,0,1,0,0,6,0], [0,8,0,1,5,4,1,8,7], [7,2,5,4,6,5,4,2,5], [1,8,4,3,6,3,6,8,6], [1,8,4,1,3,4,1,8,7], [-1,6,-1,-1,2,-1,-1,6,-1], [-1,6,-1,-1,2,-1,-1,6,-1], [-1,3,-1,-1,8,-1,-1,3,-1], [-1,6,-1,-1,2,-1,-1,6,-1], [-1,3,-1,-1,8,-1,-1,3,-1], [-1,3,-1,-1,8,-1,-1,3,-1], [8,2,8,6,3,6,8,2,8], [2,8,2,3,6,3,2,8,2], [3,6,3,2,8,2,3,6,3], [6,3,6,8,2,8,6,3,6]] }
```

**Comment by MiniMage7** [comment]
> Also playing Island of insights and stuck on one puzzle in particular that the website cant handle. The local version would be nice because this probably wont be the only one I get stuck on. ![ioipuzzle](https://private-user-images.githubusercontent.com/161029933/307310442-0c23d63e-79ae-4670-8c52-8a700d22bae5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3MDEzODYsIm5iZiI6MTcwODcwMTA4NiwicGF0aCI6Ii8xNjEwMjk5MzMvMzA3MzEwNDQyLTBjMjNkNjNlLTc5YWUtNDY3MC04YzUyLThhNzAwZDIyYmFlNS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyM1QxNTExMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MjlkNzUxYWNkNDFlYjM0Mjc0ODU2Y2EzNWM5MzVhYjc2NWU5OGUwNmFhODgyYTc3OTVhNmNhNGU0NmE3Mzg1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5g4ChlAbtAvKrjvr6rrgoKv30V58C5OUe3dvwHYUGvA)

This puzzle is probably the worst puzzle in the game for a bot to solve. There are so many moves that are obviously wrong to us, but the bot would spend a *very* long time trying. It's bad enough that I'm worried that even making a local hosted one will still take a long time with this. I won't know until I try though.

**Comment by MiniMage7** [comment]
> > Also playing Island of insights and stuck on one puzzle in particular that the website cant handle. The local version would be nice because this probably wont be the only one I get stuck on. ![ioipuzzle](https://private-user-images.githubusercontent.com/161029933/307310442-0c23d63e-79ae-4670-8c52-8a700d22bae5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3MDEzODYsIm5iZiI6MTcwODcwMTA4NiwicGF0aCI6Ii8xNjEwMjk5MzMvMzA3MzEwNDQyLTBjMjNkNjNlLTc5YWUtNDY3MC04YzUyLThhNzAwZDIyYmFlNS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyM1QxNTExMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MjlkNzUxYWNkNDFlYjM0Mjc0ODU2Y2EzNWM5MzVhYjc2NWU5OGUwNmFhODgyYTc3OTVhNmNhNGU0NmE3Mzg1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5g4ChlAbtAvKrjvr6rrgoKv30V58C5OUe3dvwHYUGvA)
> 
> This puzzle is probably the worst puzzle in the game for a bot to solve. There are so many moves that are obviously wrong to us, but the bot would spend a _very_ long time trying. It's bad enough that I'm worried that even making a local hosted one will still take a long time with this. I won't know until I try though.

I did some quick math for an estimate, but there's more than 1 trillion board states for this board. As a human you can realize that of the 14 possible first moves, at least 4 of them instantly lose the game (the 3 bottom most possible ones and the middle one above the bottom most one) (Edit: after relooking some of these moves don't instantly lose but introduce states where you can instantly lose... which still ruins the bot. mb), but the bot would have to try those and all the moves after them before realizing they're wrong. (Over a billion moves each). And each board state that leaves those moves available but still wrong will have the same effect again, but at a slightly smaller scale (like maybe 100 million each instead of a billion).

Unfortunately, I don't think this puzzle will ever be solvable without some dramatic change to the way the bot works that I can't think of, but luckily, I believe this is the only puzzle in the game like this.

**Comment by ayourk** [comment]
It would be great if there were some sort of manual solve mode, where you could play the game in the solver to test things out.

**Comment by Xepho1** [comment]
I managed to get my brother on a discord call. Fresh pair of eyes and mind helped. I don't remember the exact moves but we worked left column first. First moves should be the bottom left, Both sets (sand+hotpink)(green+blue). That should be enough to start moving the forest green tile right. from there it went pretty smoothly.

**Comment by MiniMage7** [comment]
Ok, my update: I made the whole thing into a multithreaded rust program. You can check it out at https://github.com/MiniMage7/Match3Solver/tree/rust-implementation. However, I'm not merging the branch into main. The reason being, it actually seems to be worse. It can solve the smaller puzzles easily, but once it gets to larger puzzles, even ones the website can solve, it uses all my computers resources and freezes. At first I thought it might be a bug, and maybe it is a bug I can't find (y'all are free to look and put in a pull request if you see something I couldn't), but I'm starting to think it just requires too many resources to be realistic. Sorry to disappoint :(

**Comment by ayourk** [comment]
> Ok, my update: I made the whole thing into a multithreaded rust program. You can check it out at https://github.com/MiniMage7/Match3Solver/tree/rust-implementation. However, I'm not merging the branch into main. The reason being, it actually seems to be worse. It can solve the smaller puzzles easily, but once it gets to larger puzzles, even ones the website can solve, it uses all my computers resources and freezes. At first I thought it might be a bug, and maybe it is a bug I can't find (y'all are free to look and put in a pull request if you see something I couldn't), but I'm starting to think it just requires too many resources to be realistic. Sorry to disappoint :(

I look forward to docs on how to use this thing.  I have no experience with Rust, but I do have a 9 Core CPU with 128GB RAM.

**Comment by MiniMage7** [comment]
Haha, this was my first rust program too. I figured between rust and C there would be about the same speed, but rust would be safer so I dove into that. I'll update the readme on the branch too.

**Comment by ayourk** [comment]
This solver of yours reminds me of the programming assignment of Knights Tour.

**Comment by MiniMage7** [comment]
Ok the readme is updated with an explanation on how to use. You'll need to install rust onto your pc for it for obvious reasons. I'll also attach 2 of the boards that, at least on my system, aren't solvable by the rust implementation but are by the website one.
{ "height": 10, "width": 7, "board": [[0,0,7,0,3,0,0], [0,0,4,0,4,0,0], [0,0,4,9,2,0,0], [0,0,2,5,9,0,0], [4,2,4,9,5,4,4], [4,8,8,1,8,5,1], [8,1,5,-1,7,1,2], [4,1,5,-1,7,2,8], [1,7,1,-1,3,7,2], [7,1,5,-1,7,8,3]] }
{ "height": 12, "width": 12, "board": [[0,0,0,0,0,0,4,0,0,0,0,0], [0,0,0,0,0,0,1,0,0,0,0,0], [0,0,0,0,0,4,2,0,0,0,0,0], [0,0,0,0,3,4,3,0,0,0,0,0], [0,0,0,0,2,8,8,1,0,0,0,0], [0,0,0,0,1,9,9,3,0,0,0,0], [0,0,0,0,2,3,8,4,0,0,0,0], [0,0,0,0,4,9,3,4,0,0,0,0], [2,2,5,2,5,5,7,7,1,7,1,1], [7,7,1,7,1,1,2,2,5,2,5,5], [2,2,5,2,5,5,7,7,1,7,1,1], [7,7,1,7,1,1,2,2,5,2,5,5]] }

**Comment by ayourk** [comment]
Here is the smallest possible Puzzle JSON that should be solveable:
```
{"cols":3, "rows":2, "tiles":{"0":2, "1":"A1", "2":2, "3":1, "4":"A2", "5":1}}
```

**Comment by MiniMage7** [comment]
Oh it can solve all the small ones easily. Its only the relatively larger ones that it has an issue.

**Comment by ayourk** [comment]
In case it helps, I made a small python script to convert from Puzzle JSON to the np.array() structure.
[puzjson2py.txt](https://github.com/MiniMage7/MiniMage7.github.io/files/14402862/puzjson2py.txt)

My thoughts about Puzzle JSON:  Why show tiles that have a zero value?

**Comment by MiniMage7** [comment]
The original version of this whole program did actually use python, but it's way too slow and limited for making this concept work. I show 0's because it makes is much more readable to a user without any impact on performance.

**Comment by MiniMage7** [comment]
Okay, I have finished the rust implementation and you can find it here: https://github.com/MiniMage7/Match3Solver.
Unfortunately, as expected, it can't solve this puzzle. However, to my knowledge, it is easily capable of solving all the other puzzles in the game *knock on wood*.
![image](https://github.com/MiniMage7/MiniMage7.github.io/assets/35548172/bf2ce03c-fa7c-462d-8730-8d6733818299)

I don't think I will be doing any more optimizations to the solving processes in the near future as I am now out of any ideas that could possibly improve this algorithm, however, if anyone has a definitive method to improve it, I will be willing to make it better.

**Comment by MiniMage7** [comment]
I'm going to close this thread with the opening of this one https://github.com/MiniMage7/MiniMage7.github.io/issues/6

If there are any other performance based issues, please make a new issue thread.

**Comment by ayourk** [comment]
In browser based JavaScript, is there some way where you can call a function to have it temporarily return control back to the browser so it can process its things and then come back to code exectuion?  Something like call this special function right before the solve() call.

**Comment by MiniMage7** [comment]
Yes. JavaScript has asynchronous elements, so you can likely use those to get your desired effect.

The startSolve() function in solve.js does something like this already.
