### ISSUE TITLE
No newlines in JSON please

### ISSUE THREAD

**Issue by ayourk** [MiniMage7/MiniMage7.github.io#5]
https://github.com/MiniMage7/MiniMage7.github.io/blob/becad2e287cc082d14f14821a0305f6707b75264/website.js#L367

I was testing your website out with the new Rust implementation, and saw the rust fail miserably.

**Comment by MiniMage7** [comment]
As I explained in the readme, the new lines aren't on the rust branch.

**Comment by ayourk** [comment]
Then is there a rust version of the website I can visit to get the exports?

**Comment by MiniMage7** [comment]
The rust implementation branch has the website set up without new lines. You can locally host it by using a vs code extension or similar, or by dragging the index.html into a browser.

**Comment by MiniMage7** [comment]
You can also copy the live website export into notepad and delete the 4 new lines and the recopy it.

**Comment by ayourk** [comment]
What harm is there in removing the newlines from the live version?  I don't think I've seen any other JSON implementation that injects newlines.

**Comment by MiniMage7** [comment]
There isn't any harm, but there also isn't any reason to unless the rust part becomes an official part of the project. Since I just fixed the freezing issue, after some testing I will probably be adding it.

**Comment by MiniMage7** [comment]
Although any website changes will have to wait until I get home as I'm not currently at my personal computer.
